name: CI prod

on:
  workflow_dispatch:
  push:
    tags:
      - "*"
    branches-ignore:
      - "*"
    paths-ignore:
      - '.github/**'

jobs:
  main:

    runs-on: ubuntu-latest
    name: Build and deploy

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get image tag from git
        id: image_tag
        run: |
          echo ::set-output name=TAG::${GITHUB_REF#refs/tags/}

      - name: Build prod image
        run: .github/dispatch_workflow.py
        env:
          APP_ID: ${{ secrets.APP_ID }}
          APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
          TARGET_REPO: "${{ secrets.TARGET_REPO }}"
          TAG: "${{ steps.image_tag.outputs.TAG }}"
          TARGET_WORKFLOW: "build_mainnet_aave_collaterals_bot.yaml"
